### ISSUE TITLE
Error when setting up server

### ISSUE THREAD

**Issue by iguanatamer** [JBustos22/dfsv#1]
Hi I'm trying to setup a server on ubuntu 20.04. It seems the docker is failing to pull a file because it is listed as i386 instead of amd64.

`Step 4/11 : RUN wget http://security.ubuntu.com/ubuntu/pool/main/m/mysql-5.7/libmysqlclient20_5.7.21-1ubuntu1_i386.deb
 ---> [Warning] The requested image's platform (linux/386) does not match the detected host platform (linux/amd64) and no specific platform was requested
 ---> Running in 295416b5f8f7
--2021-06-22 06:03:46--  http://security.ubuntu.com/ubuntu/pool/main/m/mysql-5.7/libmysqlclient20_5.7.21-1ubuntu1_i386.deb
Resolving security.ubuntu.com (security.ubuntu.com)... 91.189.91.39, 91.189.91.38, 2001:67c:1562::15, ...                                                                         
Connecting to security.ubuntu.com (security.ubuntu.com)|91.189.91.39|:80... connected.                                                                                            
HTTP request sent, awaiting response... 200 OK                                                                                                                                    
Length: 805968 (787K) [application/x-debian-package]                                                                                                                              
Saving to: 'libmysqlclient20_5.7.21-1ubuntu1_i386.deb'                                                                                                                            

     0K .......... .......... .......... .......... ..........  6%  971K 1s
    50K .......... .......... .......... .......... .......... 12% 2.12M 1s
   100K .......... .......... .......... .......... .......... 19% 3.50M 0s
   150K .......... .......... .......... .......... .......... 25% 3.98M 0s
   200K .......... .......... .......... .......... .......... 31% 6.77M 0s
   250K .......... .......... .......... .......... .......... 38% 7.66M 0s
   300K .......... .......... .......... .......... .......... 44% 8.12M 0s
   350K .......... .......... .......... .......... .......... 50% 8.80M 0s
   400K .......... .......... .......... .......... .......... 57% 16.0M 0s
   450K .......... .......... .......... .......... .......... 63% 12.2M 0s
   500K .......... .......... .......... .......... .......... 69% 16.6M 0s
   550K .......... .......... .......... .......... .......... 76% 13.9M 0s
   600K .......... .......... .......... .......... .......... 82% 15.7M 0s
   650K .......... .......... .......... .......... .......... 88% 18.2M 0s
   700K .......... .......... .......... .......... .......... 95% 14.2M 0s
   750K .......... .......... .......... .......              100% 24.0M=0.2s

2021-06-22 06:03:46 (5.12 MB/s) - 'libmysqlclient20_5.7.21-1ubuntu1_i386.deb' saved [805968/805968]`

**Comment by JBustos22** [comment]
Hello, sorry for taking so long to reply, this is a warning and can be ignored. The image is sets up the server in i386 because the mdd proxymod is currently only 32 bit. Did the rest of the process work?

**Comment by iguanatamer** [comment]
I forget what package it failed download but I had to edit the docker to a newer version.
