### ISSUE TITLE
Link in Dockerfile to libxml2_2.9.4+dfsg1-6.1ubuntu1.4_i386.deb is invalid

### ISSUE THREAD

**Issue by dickerdoctor** [JBustos22/dfsv#5]
In the Dockerfile there is a link to http://security.ubuntu.com/ubuntu/pool/main/libx/libxml2/libxml2_2.9.4+dfsg1-6.1ubuntu1.4_i386.deb
It can be replaced with http://security.ubuntu.com/ubuntu/pool/main/libx/libxml2/libxml2_2.9.4+dfsg1-6.1ubuntu1.8_i386.deb
the RUN dpkg -i libxml2_2.9.4+dfsg1-6.1ubuntu1.4_i386.deb can be replaced with libxml2_2.9.4+dfsg1-6.1ubuntu1.8_i386.deb

**Comment by JBustos22** [comment]
Thanks for reporting. Fixed
